In [108]:
import csv
import numpy as np
import pandas as pd
import utils 

In [137]:
data = np.genfromtxt('repeated_data.csv', delimiter=',', dtype=str)
data = np.delete(data, 0, 0)

In [138]:
data.shape

(28, 17)

In [158]:
new_data = []

# turn each game into entry in this array

def remove_blank(l):
    return list(filter(lambda a: a != '', l))

def replace_letters(l):
   return [[1,0] if x=='c' else [0, 1] for x in l]

for i in range(0, data.shape[0], 2):
    p1 = data[i]
    p2 = data[i+1]

    game = int(p1[0])
    player1 = p1[2]
    player2 = p2[2]
    p1_actions = np.array(replace_letters(remove_blank(p1[3:]))).T
    p2_actions =  np.array(replace_letters(remove_blank(p2[3:]))).T
   
    actions =  [p1_actions, p2_actions]

    new_data.append([game, player1, player2, actions])


In [150]:
df = pd.DataFrame(new_data)
df.columns = ['Game', 'Player_1', 'Player_2', 'Actions']

In [151]:
df.head()

Game Player_1    Player_2  \
0     0   Faisal  Bharathvaj   
1     1    Yuan       Dagmar   
2     2    Ehsan   Mohammend   
3     3      Tao      Rohini   
4     4    Anita        Greg   

                                             Actions  
0  [[[0, 1, 1, 1, 0], [1, 0, 0, 0, 1]], [[1, 0, 1...  
1   [[[1, 0, 0], [0, 1, 1]], [[1, 1, 0], [0, 0, 1]]]  
2  [[[1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0], [0, 0,...  
3  [[[0, 1, 0, 1, 1], [1, 0, 1, 0, 0]], [[1, 0, 0...  
4  [[[1, 1, 0, 1, 1, 1, 0], [0, 0, 1, 0, 0, 0, 1]...

In [162]:
plays = np.zeros((2,2))


for i, row in df.iterrows():
    actions = row.Actions
    for round in range( actions[0].shape[1]): # iterate over length of each game 
        s1 = actions[0][:, round]
        s2 = actions[1][:, round]
        p_outcomes = utils.p_outcomes([s1, s2])
        plays += p_outcomes
      

In [163]:
# frequency of each
plays/np.sum(plays)

array([[0.30232558, 0.18604651],
       [0.26744186, 0.24418605]])

# Model 1: Players (Quantally) Best Respond to a Sub-History

In [106]:
# def EU(actions):
#     '''
#     Given actions by both players returns the sum of payoffs for each player
#     '''

#     player_0_payoffs = [0, -1, 1, -2] # row payoffs
#     player_1_payoffs = [0, 1, -1, -2] # col payoffs

#     player_0_sum = 0
#     player_1_sum = 0
#     for round in actions.T:

#         outcome = round[ 0]*2 + round# [1]
#         player_0_sum += player_0_payoffs[outcome]
#         player_1_sum += player_1_payoffs[outcome]
    
#     return player_0_sum, player_1_sum

In [101]:
# # this is pretty much quantal regret. I'll read the paper tomorrow and implement this method

# def quantal_history_best_response(actions, k):
#     '''
#     actions : (np.array) both of the player's actions
#     k : (int) the length of the subhistory considered 
#     '''
    
#     def best_response(last_k_moves):
#         action_0_moves = np.zeros_like(last_k_moves)
#         action_1_moves = np.ones_like(last_k_moves)


#     for round in range(actions.shape[1]):
#         for player in range(0,2):
#             if k > round:
#                 last_k_moves = actions[1-player, 0:round]
#             else:
#                 last_k_moves = actions[1-player, round-k:round] # last k moves by the opponent

In [107]:

# for i, row in df.iterrows():
#     actions = row.Actions
#     print(actions)
#     print(EU(actions))
#     #quantal_history_best_response(actions, 2)
#     assert False

[[1 0 0 0 1]
 [0 1 0 1 1]]
(-3, -1)


AssertionError: 

In [211]:
def p_traj(a, s):
    '''
    Returns the probability of a sequence of actions
    a being sampled from strategy s.
    '''

    assert a.shape == s.shape
    L = a.shape[1]
    prod = 1
    for l in range(L):
        idx = np.where(a[:, l])
        print(s[:, l][idx])
        prod *= s[:, l][idx][0]

    return prod

In [207]:
data = list(df.Actions)

In [213]:

traj = data[0][0][:, 0:3]
s = np.array([[0.9, 0.1], [0.6, 0.4], [.3, .7] ]).T

p_traj(traj, s)

[0.1]
[0.6]
[0.3]


0.018

(3, 2)

In [177]:
class Level_K_Model:
    def __init__(self, K, h):
        self.K = K
        self.payoffs = np.zeros([2, 2, 2])
        self.payoffs[0, :, :] = np.array([[0, -1],
                                          [1, -2]])
        self.payoffs[1, :, :] = np.array([[0, 1],
                                         [-1, -2]])
        self.alphas = np.zeros((K, 1))
        self.h = h # the history length


    def log_likelihood(self, dataset):
        '''
        Given the dataset and the fitted model, returns the log likelihood 
        
        dataset : list of plays, each play is an np array
        '''
 
        for play in dataset: 
            for player in range(2):
                for i, k in enumerate(range(self.K)): # condition on a specific value of k for a player
                    alpha_k = self.alphas[i]
                    
                    # TODO: get probability of trajectory
                    traj = play[player]
                    other_traj  = player[1-player] # trajectory of other player
                    
                    pred_s = self.predict_traj(traj, other_traj, k)







    def predict_traj(self, traj, other_traj, K):
        '''
        returns straetgy predictions against other player
        
        '''
        L = other_traj.shape[1]
        pred_i = np.zeros((2, self.K, L)) # level-k prediction for each stage game for i
        pred_other = np.zeros((2, self.K, L)) # level-k prediction for each stage game for other player

        for l in range(L):
            # first determine level 0 strategy 
            start_hist_idx = max(l-self.h, 0)
            end_hist_idx = l

            hist_i = traj[:, start_hist_idx:end_hist_idx] # limited history of i's actions
            hist_other = other_traj[:, start_hist_idx:end_hist_idx] # limited history of -i's actions

            average_s_i = np.sum(hist_i, axis=1)/np.sum(hist_i) # average strategy of i in history
            average_s_other = np.sum(hist_other, axis=1)/np.sum(hist_other) # average strategy of -i in history

            # These become the level 0 strategies
            pred_i[:, 0, l] = average_s_i
            pred_other[:, 0, l] = average_s_other

            # Now, for higher levels:
            for k in range(1, K):
                pred_i[:, k, l] = self.compute_BR(pred_other[:, k-1, l])
                pred_other[:, k, l] = self.compute_BR(pred_i[:, k-1, l])
 
            return np.squeeze(pred_i[:, K, :]) # we only return the level K predictions



    # def predict(self, hist, other_hist):
    #     '''
    #     Uses level-K model to predict the strategy of a player given 
    #     '''




    def fit(self):
        pass




    def compute_BR(self,  s_other):
        '''
        i : index of player for whom we are computing BR
        s_other : strategy profile of other player

        NOTE: this only works with symetric payoffs
        '''
    
        #get EU of action 0
    
        s = [np.array([1, 0]), s_other]
        eu_0 = utils.expected_utility(s, self.payoffs)

        # get EU of action 1
        s = [np.array([0, 1]), s_other]
        eu_1 = utils.expected_utility(s, self.payoffs)

        # return action with greater EU
        if eu_0 >= eu_1:
            return np.array([1, 0])
        else:
            return np.array([0, 1])



    def predict(self, history=None):
        predictions = np.zeros((4, self.k)) # first two rows are mixed strategy of first player, second two are of second player
        
        # level-0 base case
        if history == None:
            predictions[0:2, 0] = np.array([0.5, 0.5])
            predictions[2:4, 0] = np.array([0.5, 0.5])
        else:
            predictions[0:2, 0] = np.sum(history[0:2, :], axis=1)/ np.sum(history[0:2, :])
            predictions[2:4, 0] = np.sum(history[2:4, :], axis=1)/ np.sum(history[2:4, :])

        
        for k in range(1, self.K):
            for player in range(0,2):
                # best respond to 1 level lower
                if player == 0:
                    predictions[0:2, k] = self.compute_BR(player,  predictions[2:4, k-1])
                else:
                    predictions[2:4, k] = self.compute_BR(player,  predictions[0:2, k-1])


        # return overall predictions
        p0_prediction = np.matmul(predictions[0:2, :], self.alphas)
        p1_prediction = np.matmul(predictions[2:4, :], self.alphas)

        return p0_prediction, p1_prediction


In [ ]:
# another one: player play as if their opponent is going to best resond to their last move
# generalization : level_0 strategy is some function of the history,  then players either use CH or level-k to produce the strategy for the next
# iteraion

In [178]:
m = Level_K_Model(K=2)
m.log_likelihood(list(df.Actions))

0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
5
6
0
1
2
3
4
5
6
0
1
2
3
4
5
6
0
1
2
3
4
5
6
0
1
2
3
0
1
2
3
0
1
2
3
0
1
2
3
0
1
2
3
4
5
6
7
8
9
10
11
12
13
0
1
2
3
4
5
6
7
8
9
10
11
12
13
0
1
2
3
4
5
6
7
8
9
10
11
12
13
0
1
2
3
4
5
6
7
8
9
10
11
12
13
0
1
0
1
0
1
0
1
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
3
0
1
2
3
0
1
2
3
0
1
2
3
0
1
0
1
0
1
0
1
0
1
2
3
4
5
6
7
8
0
1
2
3
4
5
6
7
8
0
1
2
3
4
5
6
7
8
0
1
2
3
4
5
6
7
8
0
1
2
3
4
5
6
7
8
9
10
0
1
2
3
4
5
6
7
8
9
10
0
1
2
3
4
5
6
7
8
9
10
0
1
2
3
4
5
6
7
8
9
10
